---
- name: Build Switch configuration
  hosts: MPLS_CORE
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intended variables
      tags: [build, provision, debug]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate, debug]
      import_role:
        name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cv_server
  connection: local
  gather_facts: false
  tasks:
    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'MPLS_CORE'
        configlets_prefix: 'DKNOG-AVD'
        # execute_tasks: true
        device_filter:
          - "P"
          - "PE"
          - "RR"
        search_key: hostname
        state: present
        cv_collection: v3
        apply_mode: strict
